on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      pwd: pwd  
    steps:
    - uses: actions/checkout@v2
    - run: | 
          echo "$name = pwd"
          echo "::set-output  name=${{ secrets[env.pwd] }}"
      name: op
      shell: pwsh
    - run: echo '${{steps.output.op.name}}'
      shell: pwsh
