
on: 
  #push:
   # branches:
     # - master
  workflow_dispatch:
    inputs:
      envs:
        description: 'env vars'     
        required: true
        default: '{\"include\":[{\"project\":\"foo\"},{\"project\":\"bar\"}]}'
name: build
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::${{ github.events.inputs.evs }}"
    - run: echo "${{ github.events.inputs.evs }}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: write-host ${{ matrix.project }}
      shell: pwsh
