
on: 
  push:
    branches:
      - test
  workflow_dispatch:
    inputs:
      logLeveldev:
        description: 'Log level'     
        required: true
        default: 'information'
jobs:
  build:
    strategy:
      matrix:
        node: ['dev','test']
        python: ['']
        include:
          - node: 'dev'
            python: 2.7
          - node: 'test'
            python: 3.6

    runs-on: ubuntu-latest
    environment: ${{matrix.node}}
    steps:
      - uses: actions/checkout@v2
      - uses: ./actions/
      - name: powershell
        run: |
           write-host ${{matrix.python}}
           write-host ${{matrix.node}}
        shell: pwsh
        
      
      
