on: 
  push:
    branches:
      - master
  #workflow_dispatch:
   # inputs:
    #  envs:
     #   description: 'env vars'     
      #  required: true
       # default: 'test,dev'
name: build
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
          $event = ${{ github.event_name }}
          if($event -eq 'push')
          {
          echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\"},{\"project\":\"bar\"}]}"
          }
      shell: bash
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: write-host ${{ matrix.project }}
      shell: pwsh
