name: My workflow
on: push
jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./actions/
      - name: powershell
        run: |
           get-childitem
        shell: pwsh
      
      
