name: My workflow
on: push
jobs:
  do-something:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['1','2','3']
    environment: ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./actions/
      - name: powershell
        run: |
           write-host 'hello'
           #Out-File -FilePath EmptyFile2.txt
           #git --version
           #git clone https://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:x-oauth-basic@github.com/Ajith5550/public-yamls.git
           #get-childitem
        shell: pwsh
        
      
      
