on: 
  push:
    branches:
      - master

name: build
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - id: set-matrix2
      run: |
            echo "::set-output name=matrix::${{github.event_name}}"

         
    - id: set-matrix
      run: |
          $env = 'devname'
          echo $env
          echo '${{ secrets.$env }}'
      shell: pwsh
