
on: 
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      devlogLevel:
        description: 'Log level'     
        required: true
        default: 'information'
jobs:
  do-something:
    
    strategy:
      matrix:
        node: ['dev']
    runs-on: ubuntu-latest
    environment: ${{matrix.node}}
    steps:
      - name: outputvars
        id: vars
        run: |

           #$data = (Get-Content "test.json") | ConvertFrom-Json
           write-host $data.secret
           echo "::set-output name=branch::testvalue"
        shell: pwsh
      - uses: actions/checkout@v2
      - uses: ./actions/
      - name: powershell
        run: |
           get-childitem
           write-host ${{steps.vars.outputs.branch}}
           write-host ${{inputs.devlogLevel}}
        shell: pwsh
      - name: powershell2
        run: |
           Out-File -FilePath EmptyFile2.txt
           get-childitem
        shell: pwsh
        
      
      
