on: 
  push:
    branches:
      - master

name: build
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v1.4.0
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS

          # ClientId of the Azure Service principal created.
          client-id: dc82d782-018d-4cdd-b592-cabbfc547dd0

          # TenantId of the Azure Service principal created.
          tenant-id: 2460b944-ba5e-4450-9cfb-38efd5ec2ed8
          # Azure subscriptionId
          subscription-id: 2baaaec4-bb2b-4238-ba1c-95d54ac2d312
          # Set this value to true to enable Azure PowerShell Login in addition to Az CLI login
