name: My workflow
on: push
jobs:
  do-something:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['dev','test','ppd']
    environment: ${{matrix.node}}
    steps:
      - uses: actions/checkout@v2
      - uses: ./actions/
      - name: powershell
        run: |
           write-host 'hello'
           Get-Content ".\test.json"
           $var = ${{secrets.pwd}}
           $test = '${{secrets.pwd}}'
           if($test = 'pwds')
           {
           write-host 'hurray' 
           }
           else {
           write-host 'badluck'
           }
           $test = '${{secrets.pwd}}'
           write-host 'printing secrt'+$test
           #Out-File -FilePath EmptyFile2.txt
           #git --version
           #git clone https://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:x-oauth-basic@github.com/Ajith5550/public-yamls.git
           get-childitem
           #(Get-Content ".\test.json") -replace '__pwd__' , '${{secrets.pwd}}' | Set-Content -Path ".\test.json"
           Get-Content ".\test.json"
        shell: pwsh
        
      
      
