on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: pwd
    steps:
    - uses: actions/checkout@v2
    - run: | 
          echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
          echo "::set-env name=AWS_ACCESS_KEY_ID::${{ secrets[env.AWS_ACCESS_KEY_ID] }}"
      shell: pwsh
    - run: echo '$AWS_ACCESS_KEY_ID'
      shell: pwsh
