
on: 
  push:
    branches:
      - test
  workflow_dispatch:
    inputs:
      logLeveldev:
        description: 'Log level'     
        required: true
        default: 'information'
jobs:
  build:
    strategy:
      matrix:
        python: [2.7, 3.6]
        experimental: [false]
        include:
          - python: 3.8
            experimental: true
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - uses: ./actions/
      - name: powershell
        run: |
           write-host ${{matrix.python}}
           write-host ${{matrix.experimental}}
           
        shell: pwsh
        
      
      
