
on: 
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      devlogLevel:
        description: 'Log level'     
        required: true
        default: 'information'
jobs:
  do-something:
    
    strategy:
      matrix:
        node: ['dev','test','ppd']
    runs-on: ubuntu-latest
    environment: ${{matrix.node}}
    steps:
      - uses: actions/checkout@v2
      - uses: ./actions/
      - name: powershell
        run: |
           write-host 'hello'
           write-host ${{inputs.devlogLevel}}
           #Get-Content ".\test.json"

           #$test = '${{secrets.pwd}}'
           #if($test = 'pwds')
           #{
           #write-host 'hurray' 
           #}
           ##else {
           #write-host 'badluck'
           #}
           #$test = '${{secrets.pwd}}'
           #write-host 'printing secrt'
           #Out-File -FilePath EmptyFile2.txt
           #git --version
           #git clone https://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:x-oauth-basic@github.com/Ajith5550/public-yamls.git
           #get-childitem
           #$sec = '$' + '{{secrets.' + 'pwd}}'
           #$sec
           #(Get-Content ".\test.json") -replace '__pwd__' , ${{secrets. + 'pwd'}} | Set-Content -Path ".\test.json"
           #Get-Content ".\test.json"
        shell: pwsh
        
      
      
