

on: 
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      envs:
        description: 'env vars'     
        required: true
        default: "{\"include\":[{\"environment\":\"dev1\"},{\"environment\":\"dev2\"}]}"
name: build
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name : set-matrix-from-workflow-dispatch
      if: ${{ github.EVENT_NAME == 'workflow_dispatch' }}
      id: set-matrix
      run: |
          if( '${{ github.EVENT_NAME }}' = 'workflow_dispatch')
          {
          echo "${{ github.EVENT_NAME }}"
          }
         # echo "::set-output name=matrix::${{ github.event.inputs.envs }}"
         
      shell: pwsh
 
         
    - run: echo " ${{GITHUB.EVENT_NAME}}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: write-host ${{ matrix.environment }}
      shell: pwsh
