
on: 
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      devlogLevel:
        description: 'Log level'     
        required: true
        default: 'information'
jobs:
  do-something:
    
    strategy:
      matrix:
        node: ['dev','test','ppd']
    runs-on: ubuntu-latest
    environment: ${{matrix.node}}
    steps:
      - name: outputvars
        id: vars
        run: |
           echo "::set-output name=branch::testvalue"
      - uses: actions/checkout@v2
      - uses: ./actions/
      - name: powershell
        run: |
           write-host ${{steps.SetVariables.vars.branch}}
           write-host ${{inputs.devlogLevel}}
        shell: pwsh
        
      
      
