on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      pwd: pwd  
    steps:
    - uses: actions/checkout@v2
    - run: | 
          echo '${{ secrets[env.pwd] }}'
      name: op
      shell: pwsh
