

on: 
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      envs:
        description: 'env vars'     
        required: true
        default: "{\"include\":[{\"environment\":\"dev1\"},{\"environment\":\"dev2\"}]}"
name: build
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - if: ${{ github.ref == 'master' }}
      id: set-matrix
      run: |
          
          #echo "Env: ${{ github.event.type }}" 
          echo "::set-output name=matrix::${{ github.event.inputs.envs }}"
         
    - run: echo " ${{GITHUB.WORKFLOW}}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: write-host ${{ matrix.environment }}
      shell: pwsh
