name: My workflow
on: push
jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./actions/
      - name: powershell
        run: |
           Out-File -FilePath EmptyFile2.txt
           git --version
           git clone https://Ajith5550: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@github.com/Ajith5550/public-yamls.git
           get-childitem
        shell: pwsh
      
      
