o
on: 
  push:
    branches:
      - test
  workflow_dispatch:
    inputs:
      logLeveldev:
        description: 'Log level'     
        required: true
        default: 'information'
jobs:
  do-something:
    
    strategy:
      matrix:
        node: ['dev']
    runs-on: ubuntu-latest
    environment: ${{matrix.node}}
    steps:
      - uses: actions/checkout@v2
      - uses: ./actions/
      - name: powershell
        run: |
           write-host ${{matrix.node}}
          echo ${{inputs.logLeveldev}}
           
        shell: pwsh
        
      
      
