
on: 
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      envs:
        description: 'env vars'     
        required: true
        default: "{\"include\":[{\"environment\":\"dev1\"},{\"environment\":\"dev2\"}]}"
name: build
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: |
          $event = ${{ github.event.type }}
          echo $event
          $environments = ${{ github.event.inputs.envs }}
          if ( $environments  != '')
          {
          echo "::set-output name=matrix::${{ github.event.inputs.envs }}"
          }
          else
          {
          echo "::set-output name=matrix::{\"include\":[{\"environment\":\"dev1\"},{\"environment\":\"dev2\"}]}"
          }
      shell: pwsh
    - run: echo "${{ github.event.inputs.envs }}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: write-host ${{ matrix.environment }}
      shell: pwsh
