

on: 
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      envs:
        description: 'env vars'     
        required: true
        default: "{\"include\":[{\"environment\":\"dev1\"},{\"environment\":\"dev2\"}]}"
name: build
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name : set-matrix-from-workflow-dispatch
      if: ${{ github.EVENT_NAME == 'workflow_dispatch' }}
      id: set-matrix
      run: |
          $event = '${{ github.EVENT_NAME }}'
          if( $event = 'workflow_dispatch')
          {
          echo "::set-output name=matrix::${{ github.event.inputs.envs }}"
          }
          else
          {
          $env = '{\"include\":[{\"environment\":\"dev1\"},{\"environment\":\"dev2\"}]}'
          echo "::set-output name=matrix::$env"
          }
      shell: pwsh
      
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: write-host ${{ matrix.environment }}
      shell: pwsh
